quarkus:
  mailer:
    auth-methods: ${SMTP_AUTH_METHODS:}
    host: ${SMTP_HOST:host.not.set}
    port: ${SMTP_PORT}
    start-tls: ${SMTP_TLS:DISABLED}
    ssl: ${SMTP_SSL:false}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    from: ${DEFAULT_EMAIL_FROM}
  quartz:
    clustered: false
    store-type: ram
    thread-count: 2 # should be configured according to an amount of scheduled tasks
  log:
    category:
      quarkus-mailer:
        level: WARN

application:
  database:
    type: h2
