quarkus:
  datasource:
    db-kind: ${application.database.type}
    jdbc:
      url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:db/expected_schema.sql' # remove after migrations
  quartz:
    clustered: false
    store-type: ram
    thread-count: 2 # should be configured according to an amount of scheduled tasks

application:
  database:
    type: h2
