quarkus:
  http:
    auth:
      form:
        enabled: true
        cookie-name: SESSION
        post-location: /api/admin/login
        username-parameter: username
        password-parameter: password
        login-page: '' # disabled
        error-page: '' # disabled
        landing-page: '' # disabled
      session:
        encryption-key: ${SESSION_ENCRYPTION_KEY:change-me-change-me-change-me}
      permission:
        form:
          auth-mechanism: form
          paths: /api/admin/*
          policy: authenticated
    cors:
      ~: true # 'true' for development
      origins: 'http://localhost:8080,http://localhost:9001'
      access-control-allow-credentials: true

admin:
  console:
    username: ${ADMIN_CLIENT_USERNAME:username}
    password: ${ADMIN_CLIENT_PASSWORD:password}
