quarkus:
  datasource:
    db-kind: postgresql

"%test":
  quarkus:
    log:
      category:
        "io.mailit.persistence.postgresql":
          level: DEBUG

"%prod":
  quarkus:
    datasource:
      username: ${DATABASE_USERNAME:admin}
      password: ${DATABASE_PASSWORD:admin}
      jdbc:
        url: jdbc:${DATABASE_URL:postgresql://localhost:5432/mail_it}
      reactive:
        url: ${DATABASE_URL:postgresql://localhost:5432/mail_it}
