quarkus:
  datasource:
    db-kind: ${application.database.type}
  liquibase:
    change-log: db/changelog/master.xml
    migrate-at-start: true
  quartz:
    clustered: false
    store-type: ram
    thread-count: 2 # should be configured according to an amount of scheduled tasks

application:
  database:
    type: h2
