quarkus:
  quartz:
    clustered: false
    store-type: ram
    thread-count: 2 # should be configured according to an amount of scheduled tasks

application:
  database:
    type: h2

"%test":
  quarkus:
    scheduler:
      enabled: false
