name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Set up Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Run checks
      run: ./gradlew check
