name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: corretto
        
    - name: Set up Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Run checks
      run: ./gradlew check

  dependabot-automerge:
    runs-on: ubuntu-latest

    needs: test
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}

    permissions:
      pull-requests: write
      issues: write
      repository-projects: write

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}

      - name: Approve and merge the PR
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review --approve --body "@dependabot squash and merge" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
